### PR TITLE
Configure from email addresses

### PR DESCRIPTION
**Pull request by jenmccarthy**
Changes to Mailgun emails for payment notifications (success and failure) to use ENV variables.  Also, changes to Mailgun emails for assessment reviews to use ENV variables.

### CODE REVIEW

**Comment by michaelrkn** [comment]
It appears this is branched off of the Cohort start date branch, so all of the tests are failing when merged with master. Next time, branch each feature off master. Thanks!

**Comment by michaelrkn** [comment]
I'll review this once we have the cohort stuff merged into master.

**Comment by jenmccarthy** [comment]
What happens when the build fails because of a 400 communication error with Mailgun?

**Comment by michaelrkn** [comment]
Does it pass locally?

**Comment by jenmccarthy** [comment]
yep, tests pass locally

**Comment by michaelrkn** [comment]
Oh I see. The ENV variable isn't set in Travis, so Mailgun raises an exception because the from address is invalid. You can set it at https://travis-ci.org/epicodus/epicenter/settings/env_vars. There might be something we have to figure out to give you access to Travis.

**Comment by jenmccarthy** [comment]
Awesome, I was granted access and I've just added the new ENV variables. Lets see if that works!

**Comment by jenmccarthy** [comment]
Great! Looks like you can review what I've done!

**Comment by michaelrkn** [comment]
Looks good! One last thing - update the README to include these ENV vars. Then go ahead and merge.

**Pull request merged**
